id = "underground-theme"
name = "Underground theme"
version = "1.0.0"
schema_version = 1
authors = ["Andrey Yurtaev <mdrdnt@gmail.com>"]
description = "Underground theme for Zed editor"
repository = "https://github.com/i-amdroid/zed-underground-theme"
